[env]
SOPS_AGE_KEY_FILE = "{{ env.HOME }}/.config/sops/age.txt"
GITHUB_TOKEN = { value = "{{ get_env(name='GITHUB_TOKEN', default=exec(command='{ echo protocol=https; echo host=github.com; echo; } | git credential fill 2>/dev/null | sed -n \"s/^password=//p\"')) }}", tools = true }
GITLAB_TOKEN = { value = "{{ get_env(name='GITLAB_TOKEN', default=exec(command='{ echo protocol=https; echo host=gitlab.com; echo; } | git credential fill 2>/dev/null | sed -n \"s/^password=//p\"')) }}", tools = true }
GITEA_TOKEN = { value = "{{ get_env(name='GITEA_TOKEN', default=exec(command='{ echo protocol=https; echo host=git.ckoliber.dev; echo; } | git credential fill 2>/dev/null | sed -n \"s/^password=//p\"')) }}", tools = true }

[tools]
jq = "1.8.1"
yq = "4.54.1"
gh = "2.92.0"
glab = "1.97.0"
shfmt = "3.13.1"
codex = "0.143.0"
claude = "2.1.205"
opencode = "1.17.17"
docker-cli = "29.3.0"
kubelogin = "1.36.1"
talosctl = "1.12.6"
kubectl = "1.36.1"
k9s = "0.50.18"

[tools."http:tea"]
version = "0.16.0"
platforms.linux-arm64.url = "https://gitea.com/gitea/tea/releases/download/v{{version}}/tea-{{version}}-linux-arm64"
platforms.macos-arm64.url = "https://gitea.com/gitea/tea/releases/download/v{{version}}/tea-{{version}}-darwin-arm64"
